### PR TITLE
build pr branches based on main

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
@dovholuknf this is ready for review

**Comment by qrkourier** [comment]
@dovholuknf ready for review; the purpose of this PR is to resolve associated issue https://github.com/openziti/ziti-console/issues/290 which addresses the problem of not testing PR branches before merging to the trunk branch

**Comment by qrkourier** [comment]
@rgallettonf Here's a proposed safety net to reduce the risk of merging a breaking change to the main branch. Whenever we decommission the node-api build (some months after we deprecate it with the SPA build and docs and stuff), then we should switch this PR branch build over to an SPA build, if not sooner. 

I used this Docker build because it exercises the same architectures that we're currently releasing each cycle: arm64, amd64. It felt important to do it this way because I remember that time I introduced a change that only broke the arm64 build!

**Comment by dovholuknf** [comment]
@qrkourier can you break this build so that people will know what it looks like/what to look for?

**Comment by rgallettonf** [comment]
@qrkourier I like the idea. If this will prevent merges that introduce build breaking changes, I'm all for it.

**Comment by qrkourier** [comment]
> @qrkourier I like the idea. If this will prevent merges that introduce build breaking changes, I'm all for it.

@rgallettonf, I've committed a breaking change to simulate how any branch will appear in the GitHub.com UI when it does not build. Basically, a red :x: shows up in several places.

The CI job builds everything, so it provides good coverage for now.

If you will unbreak this branch and push it up the we can accept the test into the main branch.

**Comment by rgallettonf** [comment]
> > @qrkourier I like the idea. If this will prevent merges that introduce build breaking changes, I'm all for it.
> 
> @rgallettonf, I've committed a breaking change to simulate how any branch will appear in the GitHub.com UI when it does not build. Basically, a red ❌ shows up in several places.
> 
> The CI job builds everything, so it provides good coverage for now.
> 
> If you will unbreak this branch and push it up the we can accept the test into the main branch.

Looks good to me. Committed the fix for this and observed the build check pass.

**Pull request merged**
