### PR TITLE
tidy banner text

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Comment by qrkourier** [comment]
:vomiting_face: 

Screenshot-4

**Review by rgallettonf — APPROVED** [review]

**Comment by dovholuknf** [comment]
and now it's boring and looks off balance. let's not churn on things like this at this time?

**Comment by qrkourier** [comment]
:tada: 
Screenshot-6

**Comment by dovholuknf** [comment]
Still don't want to change this

**Pull request closed without merging**
