### PR TITLE
Fix rendering of complex config schemas on create/edit service form

### LINKED ISSUE #291: Issues when creating/editing configs on advanced service form
* Can't edit/add some actions after toggling back and forth between JSON and form view's
* Editing configs with larger schemas can be difficult. Nested object/array properties should have expand/collapse behavior

### PR DESCRIPTION
**Pull request by rgallettonf**
closes #291 

* Added expand collapse behavior for Object/Array property types
* Adjusted whitespace, padding, margins, and sizing of fields
* Use of css variables where applicable
* Fixed rendering of config when toggling back and forth between JSON & form views

Screen Shot 2024-04-02 at 8 25 02 AM

### CODE REVIEW

**Review by lfouts — APPROVED** [review]

**Comment by dovholuknf** [comment]
i provided a bunch of usability-related things to ryan via DM. some of them are just overall UX issues that I think should be solved.
image

this situation should not have allowed me to hit save and once i hit save the configurations were invalid
image

i closed the UI and then clicked save again and all of them failed. it'd be better if this could override/update -- or have full expectations that it will succeed.

**Comment by dovholuknf** [comment]
the "service attributes" should work like the identiteis and show me other attributes. i added `clint's service` above as you can see, but when i click on the attribute nothing is shown. it should show all the existing service attributes. 
image

even typing yields no service attributes:
image

**Comment by dovholuknf** [comment]
intercepts should verify that the intercept contains at least one period -- aka not "hostname looking" like this:
image

It's fine for the host/bind side to use a hostname though

**Comment by dovholuknf** [comment]
the modal that comes up doesn't work:

menu-inverted

**Comment by dovholuknf** [comment]
the json view has no validation associated to it. this showed me a 'green' success growler and shouldn't even been able to click save.

shouldnt_be_able_to_save

**Review by dovholuknf — CHANGES_REQUESTED** [review]
lots of usability changes/testing still needed

**Comment by rgallettonf** [comment]
@dovholuknf  The issues noted above should be addressed with the latest commit.

**Review by dovholuknf — APPROVED** [review]

**Pull request merged**
